apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init
#  namespace: cockroachdb
  labels:
    app: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v22.2.2
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/bash"
          - "-ecx"
          - "/cockroach/cockroach init --insecure --host=cockroachdb-1.cockroachdb"
      restartPolicy: OnFailure
